version: "3.9"
services:
  db:
    image: mysql:8
    container_name: hotelsystem_db
    environment:
      MYSQL_DATABASE: hotelsystem_db
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -pmysql"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: .
    container_name: hotelsystem_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hotelsystem_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    depends_on:
      - db
    restart: on-failure